/**
 * The outbound webhook: content-service's one integration point back into your site.
 *
 * @remarks
 * Lives in the main entry rather than in `./next`, because the payload and the signature are
 * framework-independent — only the route handler is Next-specific.
 *
 * **This replaced a single bespoke revalidation POST.** The service now emits the estate's
 * standard event envelope, so the whole body changed shape: `body.type` became `body.event_type`,
 * `body.slug` moved to `body.data.page.slug`, `body.published_at` became `body.occurred_at`, and
 * `slug: null` meaning "revalidate everything" became a dedicated `site.revalidation_requested`
 * event. What did **not** change is the part receivers usually get wrong: the signing algorithm,
 * the signed string, the raw-body rule and the 300-second skew window are frozen.
 *
 * **The signing secret changed and the diff does not show it.** It is per **endpoint** now,
 * generated by the service and shown once, and the old per-site secret cannot be carried across —
 * it was stored under a different AAD, so nothing existing decrypts under the new binding. Until
 * an operator hands you the new `whsec_…` value, every delivery fails verification and
 * dead-letters; after five, the endpoint is auto-disabled.
 */

import { type VerifyFailure, verifySignedBody } from "@lazslov/api-core";

/** The signature header: `sha256=` plus lowercase hex. */
export const signatureHeader = "X-Signature";

/** The signing timestamp header: Unix **seconds**, not milliseconds. */
export const timestampHeader = "X-Signature-Timestamp";

/**
 * The event id header. **This is the dedupe key.**
 *
 * @remarks
 * Stable across every retry *and* every operator redelivery. Dedupe on this, never on
 * {@link deliveryIdHeader}, which changes per attempt and would let a retry through.
 */
export const eventIdHeader = "X-Event-Id";

/** Unique per HTTP attempt. For correlating one delivery in two parties' logs; never a dedupe key. */
export const deliveryIdHeader = "X-Delivery-Id";

/**
 * The event types content-service emits today.
 *
 * @remarks
 * A hint for a `switch`, deliberately **not** the type of {@link ContentEvent.event_type}: a
 * receiver must tolerate a type it has never heard of and still answer `2xx`, so narrowing the
 * field would make the compiler push callers towards an exhaustive switch that rejects the future.
 *
 * `GET /v1/admin/event-types` serves the live catalogue as data.
 */
export type KnownContentEventType =
  | "page.published"
  | "collection_item.published"
  | "collection_item.archived"
  | "record.created"
  | "site.revalidation_requested";

/** Which tenant an event belongs to. */
export interface ContentEventTenant {
  /** Always `"site"` from this service. */
  readonly kind: string;
  readonly public_id: string;
}

/**
 * One delivered event, in the estate's standard envelope.
 *
 * @remarks
 * Members are `snake_case`, as they arrive. The SDK does not rename them: an envelope a receiver
 * may also log, forward or store is easier to match against the service's own documentation when
 * it reads the same on both sides.
 */
export interface ContentEvent {
  /** UUIDv7, equal to `X-Event-Id`. The dedupe key. */
  readonly event_id: string;
  /**
   * The **only** thing to branch on.
   *
   * @remarks
   * A `string` rather than {@link KnownContentEventType}, because an unknown type is a normal
   * delivery rather than an error — see {@link ContentEvent} and the handler contract.
   */
  readonly event_type: string;
  /** The version these bytes were rendered at — your endpoint's pin. */
  readonly contract_version: number;
  /** ISO 8601 UTC. **When the fact became true**, not when it was sent. */
  readonly occurred_at: string;
  /** `"content-service"`. What makes a multi-service receiver's logs legible. */
  readonly service: string;
  /** The lamido-admin account id, or `null` for a site nobody has paired. */
  readonly account_id: string | null;
  /**
   * The sending site.
   *
   * @remarks
   * You do **not** need to check it: the signing secret is per endpoint, so a valid signature
   * already proves who sent it. Checking it as well only adds a way to reject your own deliveries.
   */
  readonly tenant: ContentEventTenant;
  /** Stable across a whole causal chain. Equals `event_id` on everything this service emits. */
  readonly correlation_id: string;
  /** The `event_id` that caused this one. **Never absent**; `null` on everything this service emits. */
  readonly causation_id: string | null;
  /** `0` on everything this service emits. */
  readonly hop: number;
  /**
   * Exactly one block, named by the event type's own prefix.
   *
   * @remarks
   * `page.published` ⟹ `data.page`. Use {@link subjectOf} rather than a per-type branch: one line
   * then locates the subject of any event, including types that do not exist yet.
   *
   * **The payload is a snapshot and the API is authoritative.** If a read and an event disagree,
   * the read is right and the event is old — a delivery that arrives after a dead-letter and a
   * redelivery may describe version 7 while the page is on version 9.
   */
  readonly data: Record<string, unknown>;
}

/**
 * The event's subject block, found through its type prefix.
 *
 * @param event - A verified event.
 * @returns The block, or `undefined` when the event carries none under its prefix.
 * @remarks
 * The mechanical alternative to a `switch` per event type. `collection_item.archived` ⟹
 * `data.collection_item`, and an event type this SDK has never seen resolves just as well.
 *
 * @example
 * ```ts
 * const page = subjectOf(event) as { slug?: string } | undefined;
 * if (page?.slug) revalidatePath(`/${page.slug}`);
 * ```
 */
export function subjectOf(event: ContentEvent): unknown {
  const prefix = event.event_type.split(".")[0];
  return prefix === undefined ? undefined : event.data[prefix];
}

/** The outcome of {@link verifyContentWebhook}. */
export type ContentWebhookVerdict =
  | { readonly ok: true; readonly event: ContentEvent }
  | {
      readonly ok: false;
      /** `"malformed_body"` is this package's own; the rest come from the shared verifier. */
      readonly reason: VerifyFailure | "malformed_body";
    };

/** What the verifier needs. */
export interface ContentWebhookInput {
  /**
   * The endpoint's signing secret, `whsec_…`. Used whole.
   *
   * @remarks
   * **Per endpoint, not per site.** Shown in exactly one response — `POST …/webhook-endpoints` or
   * `POST …/rotate-secret` — and unrecoverable afterwards. Confirm a new one with
   * `POST …/webhook-endpoints/{public_id}/test` before trusting it: that probe is signed exactly
   * as a real delivery is, and it needs nobody to publish anything.
   */
  readonly secret: string;
  /**
   * The request body **as text**, read before any parsing.
   *
   * @remarks
   * A string and not an object on purpose: `JSON.parse` then re-serialise reorders keys and changes
   * whitespace, and the signature stops matching. In an edge runtime that is the likeliest cause of a
   * `401` on a delivery that is perfectly valid.
   */
  readonly rawBody: string;
  /** The request's headers, or anything with a compatible `get`. */
  readonly headers: Pick<Headers, "get">;
  /** Default 300 seconds, which is what the service documents. */
  readonly toleranceSeconds?: number;
  /** Injectable so a fixture is deterministic. */
  readonly nowSeconds?: number;
}

/**
 * Verify a delivery, and parse it only if the signature holds.
 *
 * @param input - The secret, the raw body and the request headers.
 * @returns The event on success; a reason on failure. **Never throws.**
 * @remarks
 * The event is reachable *only* through a valid verdict, which is what makes "verify before you
 * parse" structural rather than a rule to remember. A handler maps the failures itself:
 * `stale_timestamp` and `malformed_body` are a `400`, `missing_signature` and `bad_signature` a
 * `401`.
 *
 * The timestamp is inside the signed string on purpose — signing the body alone would let a captured
 * delivery be replayed forever under a fresh header — so a delivery more than five minutes old is
 * rejected even when the digest matches.
 *
 * **Dedupe on `X-Event-Id`, and answer `2xx` for an event type you do not handle.** The service
 * retries, and an operator can redeliver; both carry the same event id. Answering non-2xx for an
 * unrecognised type makes the service dead-letter a delivery that was fine, and after five the
 * endpoint is disabled.
 *
 * @example
 * ```ts
 * const verdict = await verifyContentWebhook({
 *   secret: process.env.CONTENT_WEBHOOK_SECRET!,
 *   rawBody: await request.text(),
 *   headers: request.headers,
 * });
 * if (!verdict.ok) {
 *   const bad = verdict.reason === "stale_timestamp" || verdict.reason === "malformed_body";
 *   return new Response(verdict.reason, { status: bad ? 400 : 401 });
 * }
 * revalidateTag(CONTENT_TAG);   // the tag your reads set — a mismatch fails silently
 * ```
 */
export async function verifyContentWebhook(
  input: ContentWebhookInput,
): Promise<ContentWebhookVerdict> {
  const verdict = await verifySignedBody({
    secret: input.secret,
    rawBody: input.rawBody,
    signature: input.headers.get(signatureHeader),
    timestamp: input.headers.get(timestampHeader),
    ...(input.toleranceSeconds === undefined ? {} : { toleranceSeconds: input.toleranceSeconds }),
    ...(input.nowSeconds === undefined ? {} : { nowSeconds: input.nowSeconds }),
  });

  if (!verdict.ok) return { ok: false, reason: verdict.reason };

  const event = parseEvent(input.rawBody);
  return event === null ? { ok: false, reason: "malformed_body" } : { ok: true, event };
}

/**
 * Read the delivery body.
 *
 * @returns The event, or `null` when the body is not one.
 * @remarks
 * Checks only the envelope members the contract marks *always present*, and never the event type
 * against a list: an unrecognised type is a valid delivery this receiver simply does not act on,
 * and rejecting it here would dead-letter it.
 */
function parseEvent(rawBody: string): ContentEvent | null {
  let body: unknown;
  try {
    body = JSON.parse(rawBody);
  } catch {
    return null;
  }

  if (typeof body !== "object" || body === null) return null;
  const candidate = body as Record<string, unknown>;

  const tenant = candidate.tenant as Record<string, unknown> | null | undefined;
  if (typeof candidate.event_id !== "string") return null;
  if (typeof candidate.event_type !== "string") return null;
  if (typeof candidate.occurred_at !== "string") return null;
  if (typeof tenant !== "object" || tenant === null) return null;
  if (typeof tenant.public_id !== "string") return null;
  if (typeof candidate.data !== "object" || candidate.data === null) return null;

  return {
    event_id: candidate.event_id,
    event_type: candidate.event_type,
    contract_version:
      typeof candidate.contract_version === "number" ? candidate.contract_version : 1,
    occurred_at: candidate.occurred_at,
    service: typeof candidate.service === "string" ? candidate.service : "content-service",
    account_id: typeof candidate.account_id === "string" ? candidate.account_id : null,
    tenant: {
      kind: typeof tenant.kind === "string" ? tenant.kind : "site",
      public_id: tenant.public_id,
    },
    // Equal to `event_id` on everything this service emits, which is the documented fallback.
    correlation_id:
      typeof candidate.correlation_id === "string" ? candidate.correlation_id : candidate.event_id,
    causation_id: typeof candidate.causation_id === "string" ? candidate.causation_id : null,
    hop: typeof candidate.hop === "number" ? candidate.hop : 0,
    data: candidate.data as Record<string, unknown>,
  };
}
